// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://idwkrddbdyakmpshsvtd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlkd2tyZGRiZHlha21wc2hzdnRkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2NDg2ODEsImV4cCI6MjA3MTIyNDY4MX0.q_VRJrfAeha5q-qPC2ivJaFqX8yJyxjmRKFXnIuBObA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});